spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://localhost:3306/baas_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: baas_user
    password: baas_password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8089/realms/baas/protocol/openid-connect/certs}
  #          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8089/realms/baas}
  cloud:
    function:
      definition: recordTransactionCommand
    stream:
      bindings:
        recordTransactionCommand-in-0:
          destination: record-transaction-command
          group: transaction-service
          content-type: application/json
        transactionRecordedEvent-out-0:
          destination: transaction-recorded-event
          content-type: application/json
        transactionFailedEvent-out-0:
          destination: transaction-failed-event
          content-type: application/json
      kafka:
        binder:
          brokers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
          auto-create-topics: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: 8084
logging:
  pattern:
    # Console logging pattern with correlation ID
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{trace_id:-N/A} %X{span_id:-N/A}] [${spring.application.name}] %logger{40} - %msg%n"
  
  level:
    # Application-specific logging levels
    com.rajeswaran: INFO
    
    # Framework logging levels (reduce noise)
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    org.springframework.cloud.stream: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    
    # Root level
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
