spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/baas_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: baas_user
    password: baas_password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    discovery:
      enabled: true
    function:
      definition: validatePaymentCommand;accountBalanceUpdatedEvent;paymentFailedEvent;updatePaymentStatusCommand
    stream:
      default-binder: kafka
      bindings:
        validatePaymentCommand-in-0:
          destination: validate-payment-command
          group: payment-service
          content-type: application/json
        paymentValidatedEvent-out-0:
          destination: payment-validated-event
        paymentValidationFailedEvent-out-0:
          destination: payment-validation-failed-event
        updatePaymentStatusCommand-in-0:
          destination: update-payment-status-command
          group: payment-service
          content-type: application/json
        paymentStatusUpdatedEvent-out-0:
          destination: payment-status-updated-event
      kafka:
        binder:
          brokers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
          auto-create-topics: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8089/realms/baas/protocol/openid-connect/certs}
#          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8089/realms/baas}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: 8083
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId:-N/A}] %logger{36} - %msg%n"
  level:
    com.rajeswaran: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

