spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/baas_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: baas_user
    password: baas_password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    discovery:
      enabled: true
    function:
      definition: createUserCommand;deleteUserCommand
    stream:
      bindings:
        createUserCommand-in-0:
          destination: create-user-command
          group: user-service
          content-type: application/json
        deleteUserCommand-in-0:
          destination: delete-user-command
          group: user-service
          content-type: application/json
        userCreatedEvent-out-0:
          destination: user-created-event
          content-type: application/json
        userCreationFailedEvent-out-0:
          destination: user-creation-failed-event
          content-type: application/json
        userDeletedEvent-out-0:
          destination: user-deleted-event
          content-type: application/json
        userDeletionFailedEvent-out-0:
          destination: user-deletion-failed-event
          content-type: application/json
      kafka:
        binder:
          brokers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8089/realms/baas/protocol/openid-connect/certs}
#          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8089/realms/baas}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: 8082
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{trace_id:-N/A} %X{span_id:-N/A}] [${spring.application.name}] %logger{40} - %msg%n"
  level:
    com.rajeswaran: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    org.springframework.cloud.stream: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

