spring:
  application:
    name: saga-orchestrator-service
  datasource:
    url: jdbc:mysql://localhost:3306/baas_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: baas_user
    password: baas_password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8089/realms/baas/protocol/openid-connect/certs}
          # issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8089/realms/baas}
  cloud:
    function:
      definition: userCreatedEvent;userCreationFailedEvent;
        accountOpenedEvent;accountOpenFailedEvent;
        userDeletedEvent;userDeletionFailedEvent;
        paymentValidatedEvent;paymentValidationFailedEvent;
        paymentProcessedEvent;paymentFailedEvent;
        transactionRecordedEvent;transactionFailedEvent;
        paymentStatusUpdatedEvent;
        sendNotificationCommand
    stream:
      bindings:
        # UserOnboardingSaga
        createUserCommand-out-0:
          destination: create-user-command
        userCreatedEvent-in-0:
          destination: user-created-event
          group: saga-orchestrator-service
          content-type: application/json
        userCreationFailedEvent-in-0:
          destination: user-creation-failed-event
          group: saga-orchestrator-service
          content-type: application/json

        accountOpenCommand-out-0:
          destination: account-open-command
        accountOpenedEvent-in-0:
          destination: account-opened-event
          group: saga-orchestrator-service
          content-type: application/json
        accountOpenFailedEvent-in-0:
          destination: account-open-failed-event
          group: saga-orchestrator-service
          content-type: application/json

        deleteUserCommand-out-0:
          destination: delete-user-command
        userDeletedEvent-in-0:
          destination: user-deleted-event
          group: saga-orchestrator-service
          content-type: application/json
        userDeletionFailedEvent-in-0:
          destination: user-deletion-failed-event
          group: saga-orchestrator-service
          content-type: application/json


        #  PaymentProcessingSaga
        validatePaymentCommand-out-0:
          destination: validate-payment-command
        paymentValidatedEvent-in-0:
          destination: payment-validated-event
          group: saga-orchestrator-service
          content-type: application/json
        paymentValidationFailedEvent-in-0:
          destination: payment-validation-failed-event
          group: saga-orchestrator-service
          content-type: application/json

        processPaymentCommand-out-0:
          destination: process-payment-command
        paymentProcessedEvent-in-0:
          destination: payment-processed-event
          group: saga-orchestrator-service
          content-type: application/json
        paymentFailedEvent-in-0:
          destination: payment-failed-event
          group: saga-orchestrator-service
          content-type: application/json

        recordTransactionCommand-out-0:
          destination: record-transaction-command
        transactionRecordedEvent-in-0:
          destination: transaction-recorded-event
          group: saga-orchestrator-service
          content-type: application/json
        transactionFailedEvent-in-0:
          destination: transaction-failed-event
          group: saga-orchestrator-service
          content-type: application/json

        updatePaymentStatusCommand-out-0:
          destination: update-payment-status-command
        paymentStatusUpdatedEvent-in-0:
          destination: payment-status-updated-event
          group: saga-orchestrator-service
          content-type: application/json

        sendNotificationCommand-out-0:
          destination: send-notification-command
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{correlationId}] %msg%n"
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN


