spring:
  application:
    name: saga-orchestrator-service
  datasource:
    url: jdbc:mysql://localhost:3306/baas_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: baas_user
    password: baas_password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{correlationId}] %msg%n"
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN

  cloud:
    function:
      definition: sagaReplyListener
    stream:
      bindings:
        sagaReplyListener-in-0:
          destination: saga-replies
          group: saga-orchestrator-group
          content-type: application/json

        # Output bindings for saga commands (used by StreamBridge)
        createUserCommand-out-0:
          destination: create-user-command
        deleteUserCommand-out-0:
          destination: delete-user-command
        accountOpenCommand-out-0:
          destination: account-open-command
        closeAccountCommand-out-0:
          destination: close-account-command
        sendNotificationCommand-out-0:
          destination: send-notification-command
        cancelNotificationCommand-out-0:
          destination: cancel-notification-command

      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
